#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;

namespace com.squirrelbite.ava_base_setup
{
	public enum FT_Type { UnifiedExpressions = 0, SRanipal = 1, ARKit = 2 };

	public static class FTTypeMatcher
	{
		public static int Match(SkinnedMeshRenderer Smr)
		{
			int matchKind = -1;
			var bestMatch = MatchArray(UnifiedExpressions, Smr);
			if(bestMatch > 0)
				matchKind = (int)FT_Type.UnifiedExpressions;
			return matchKind;
		}

		public static float MatchArray(string[] FTSet, SkinnedMeshRenderer Smr)
		{
			int matched = 0;
			for(int i = 0; i < Smr.sharedMesh.blendShapeCount; i++)
				if(FTSet.Contains(Smr.sharedMesh.GetBlendShapeName(i)))
					matched++;
			return (float)matched / Math.Max(1, FTSet.Length);
		}

		public static readonly string[] UnifiedExpressions = new string[] {
			"EyeLookOut",
			"EyeLookOutLeft",
			"EyeLookOutRight",
			"EyeLookIn",
			"EyeLookInLeft",
			"EyeLookInRight",
			"EyeLookUp",
			"EyeLookUpLeft",
			"EyeLookUpRight",
			"EyeLookDown",
			"EyeLookDownLeft",
			"EyeLookDownRight",
			"EyeClosed",
			"EyeClosedLeft",
			"EyeClosedRight",
			"EyeSquint",
			"EyeSquintLeft",
			"EyeSquintRight",
			"EyeClosedSquintCorrective",
			"EyeClosedSquintCorrectiveLeft",
			"EyeClosedSquintCorrectiveRight",
			"EyeWide",
			"EyeWideLeft",
			"EyeWideRight",
			"EyeDilation",
			"EyeDilationLeft",
			"EyeDilationRight",
			"EyeConstrict",
			"EyeConstrictLeft",
			"EyeConstrictRight",
			"BrowDown",
			"BrowDownLeft",
			"BrowDownRight",
			"EyeClosedBrowDownCorrective",
			"EyeClosedBrowDownCorrectiveLeft",
			"EyeClosedBrowDownCorrectiveRight",
			"BrowPinchLeft",
			"BrowPinchRight",
			"BrowLowererLeft",
			"BrowLowererRight",
			"BrowUp",
			"BrowUpLeft",
			"BrowUpRight",
			"BrowInnerUp",
			"BrowInnerUpLeft",
			"BrowInnerUpRight",
			"EyeClosedBrowInnerUpCorrective",
			"EyeClosedBrowInnerUpCorrectiveLeft",
			"EyeClosedBrowInnerUpCorrectiveRight",
			"BrowOuterUp",
			"BrowOuterUpLeft",
			"BrowOuterUpRight",
			"EyeClosedBrowOuterUpCorrective",
			"EyeClosedBrowOuterUpCorrectiveLeft",
			"EyeClosedBrowOuterUpCorrectiveRight",
			"NoseSneer",
			"NoseSneerLeft",
			"NoseSneerRight",
			"NasalDilation",
			"NasalDilationLeft",
			"NasalDilationRight",
			"NasalConstrict",
			"NasalConstrictLeft",
			"NaseConstrictRight",
			"CheekSquint",
			"CheekSquintLeft",
			"CheekSquintRight",
			"CheekPuff",
			"CheekPuffLeft",
			"CheekPuffRight",
			"CheekSuck",
			"CheekSuckLeft",
			"CheekSuckRight",
			"JawOpen",
			"MouthApeShape",
			"MouthClosed",
			"JawLeft",
			"JawRight",
			"JawForward",
			"JawBackward",
			"JawClench",
			"JawMandibleRaise",
			"LipSuckUpper",
			"LipSuckUpperLeft",
			"LipSuckUpperRight",
			"LipSuckLower",
			"LipSuckLowerLeft",
			"LipSuckLowerRight",
			"LipSuckCorner",
			"LipSuckCornerLeft",
			"LipSuckCornerRight",
			"LipFunnel",
			"LipFunnelUpper",
			"LipFunnelUpperRight",
			"LipFunnelUpperLeft",
			"LipFunnelLower",
			"LipFunnelLowerRight",
			"LipFunnelLowerLeft",
			"LipPucker",
			"LipPuckerLeft",
			"LipPuckerRight",
			"MouthUpperUp",
			"MouthUpperUpLeft",
			"MouthUpperUpRight",
			"MouthLowerDown",
			"MouthLowerDownLeft",
			"MouthLowerDownRight",
			"MouthUpperDeepen",
			"MouthUpperDeepenLeft",
			"MouthUpperDeepenRight",
			"MouthLeft",
			"MouthUpperLeft",
			"MouthLowerLeft",
			"MouthRight",
			"MouthUpperRight",
			"MouthLowerRight",
			"MouthCornerPull",
			"MouthCornerPullLeft",
			"MouthCornerPullRight",
			"MouthCorner",
			"MouthCornerSlantLeft",
			"MouthCornerSlantRight",
			"MouthSmile",
			"MouthSmileLeft",
			"MouthSmileRight",
			"MouthFrown",
			"MouthFrownLeft",
			"MouthFrownRight",
			"MouthStretch",
			"MouthStretchLeft",
			"MouthStretchRight",
			"MouthSad",
			"MouthSadLeft",
			"MouthSadRight",
			"MouthDimple",
			"MouthDimpleLeft",
			"MouthDimpleRight",
			"MouthRaiser",
			"MouthRaiserUpper",
			"MouthRaiserLower",
			"MouthPress",
			"MouthPressLeft",
			"MouthPressRight",
			"MouthTightener",
			"MouthTightenerLeft",
			"MouthTightenerRight",
			"TongueOut",
			"TongueOutStep1",
			"TongueOutStep2",
			"TongueDown",
			"TongueUp",
			"TongueLeft",
			"TongueRight",
			"TongueUpLeftMorph",
			"TongueUpRightMorph",
			"TongueDownLeftMorph",
			"TongueDownRightMorph",
			"TongueRoll",
			"TongueBendDown",
			"TongueCurlUp",
			"TongueSquish",
			"TongueFlat",
			"TongueTwistLeft",
			"TongueTwistRight",
			"SoftPalateClose",
			"ThroatSwallow",
			"NeckFlexLeft",
			"NeckFlexRight",
		};
	}
}

#endif
