#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;

namespace com.squirrelbite.ava_base_setup
{
	public enum FT_Type { UnifiedExpressions = 0, SRanipal = 1, ARKit = 2 };

	public static class FTTypeMatcher
	{
		public static SkinnedMeshRenderer DetectFaceMesh(GameObject Root)
		{
			SkinnedMeshRenderer match = null;
			foreach(var candidate in Root.GetComponentsInChildren<SkinnedMeshRenderer>())
			{
				if(candidate.name.ToLower() == "body" && match == null || AnimationPathUtil.GetParentDepth(match.transform) > AnimationPathUtil.GetParentDepth(candidate.transform))
					match = candidate;
			}
			return match;
		}

		public static int Match(SkinnedMeshRenderer Smr)
		{
			int matchKind = -1;
			var bestMatch = MatchArray(UnifiedExpressions, Smr);
			if(bestMatch > 0)
				matchKind = (int)FT_Type.UnifiedExpressions;
			if(MatchArray(SRanipal, Smr) is var matchSRanipal && matchSRanipal > bestMatch)
			{
				matchKind = (int)FT_Type.SRanipal;
				bestMatch = matchSRanipal;
			}
			if(MatchArray(ARKit, Smr) is var matchARKit && matchSRanipal > bestMatch)
				matchKind = (int)FT_Type.ARKit;
			return matchKind;
		}

		public static float MatchArray(string[] FTSet, SkinnedMeshRenderer Smr)
		{
			int matched = 0;
			for(int i = 0; i < Smr.sharedMesh.blendShapeCount; i++)
				if(FTSet.Contains(Smr.sharedMesh.GetBlendShapeName(i)))
					matched++;
			return (float)matched / Math.Max(1, FTSet.Length);
		}


		// Values from (2025-11-04)
		// https://docs.google.com/spreadsheets/d/118jo960co3Mgw8eREFVBsaJ7z0GtKNr52IB4Bz99VTA

		public static readonly string[] UnifiedExpressions = new string[] {
			"EyeLookOut",
			"EyeLookOutLeft",
			"EyeLookOutRight",
			"EyeLookIn",
			"EyeLookInLeft",
			"EyeLookInRight",
			"EyeLookUp",
			"EyeLookUpLeft",
			"EyeLookUpRight",
			"EyeLookDown",
			"EyeLookDownLeft",
			"EyeLookDownRight",
			"EyeClosed",
			"EyeClosedLeft",
			"EyeClosedRight",
			"EyeSquint",
			"EyeSquintLeft",
			"EyeSquintRight",
			"EyeClosedSquintCorrective",
			"EyeClosedSquintCorrectiveLeft",
			"EyeClosedSquintCorrectiveRight",
			"EyeWide",
			"EyeWideLeft",
			"EyeWideRight",
			"EyeDilation",
			"EyeDilationLeft",
			"EyeDilationRight",
			"EyeConstrict",
			"EyeConstrictLeft",
			"EyeConstrictRight",
			"BrowDown",
			"BrowDownLeft",
			"BrowDownRight",
			"EyeClosedBrowDownCorrective",
			"EyeClosedBrowDownCorrectiveLeft",
			"EyeClosedBrowDownCorrectiveRight",
			"BrowPinchLeft",
			"BrowPinchRight",
			"BrowLowererLeft",
			"BrowLowererRight",
			"BrowUp",
			"BrowUpLeft",
			"BrowUpRight",
			"BrowInnerUp",
			"BrowInnerUpLeft",
			"BrowInnerUpRight",
			"EyeClosedBrowInnerUpCorrective",
			"EyeClosedBrowInnerUpCorrectiveLeft",
			"EyeClosedBrowInnerUpCorrectiveRight",
			"BrowOuterUp",
			"BrowOuterUpLeft",
			"BrowOuterUpRight",
			"EyeClosedBrowOuterUpCorrective",
			"EyeClosedBrowOuterUpCorrectiveLeft",
			"EyeClosedBrowOuterUpCorrectiveRight",
			"NoseSneer",
			"NoseSneerLeft",
			"NoseSneerRight",
			"NasalDilation",
			"NasalDilationLeft",
			"NasalDilationRight",
			"NasalConstrict",
			"NasalConstrictLeft",
			"NaseConstrictRight",
			"CheekSquint",
			"CheekSquintLeft",
			"CheekSquintRight",
			"CheekPuff",
			"CheekPuffLeft",
			"CheekPuffRight",
			"CheekSuck",
			"CheekSuckLeft",
			"CheekSuckRight",
			"JawOpen",
			"MouthApeShape",
			"MouthClosed",
			"JawLeft",
			"JawRight",
			"JawForward",
			"JawBackward",
			"JawClench",
			"JawMandibleRaise",
			"LipSuckUpper",
			"LipSuckUpperLeft",
			"LipSuckUpperRight",
			"LipSuckLower",
			"LipSuckLowerLeft",
			"LipSuckLowerRight",
			"LipSuckCorner",
			"LipSuckCornerLeft",
			"LipSuckCornerRight",
			"LipFunnel",
			"LipFunnelUpper",
			"LipFunnelUpperRight",
			"LipFunnelUpperLeft",
			"LipFunnelLower",
			"LipFunnelLowerRight",
			"LipFunnelLowerLeft",
			"LipPucker",
			"LipPuckerLeft",
			"LipPuckerRight",
			"MouthUpperUp",
			"MouthUpperUpLeft",
			"MouthUpperUpRight",
			"MouthLowerDown",
			"MouthLowerDownLeft",
			"MouthLowerDownRight",
			"MouthUpperDeepen",
			"MouthUpperDeepenLeft",
			"MouthUpperDeepenRight",
			"MouthLeft",
			"MouthUpperLeft",
			"MouthLowerLeft",
			"MouthRight",
			"MouthUpperRight",
			"MouthLowerRight",
			"MouthCornerPull",
			"MouthCornerPullLeft",
			"MouthCornerPullRight",
			"MouthCorner",
			"MouthCornerSlantLeft",
			"MouthCornerSlantRight",
			"MouthSmile",
			"MouthSmileLeft",
			"MouthSmileRight",
			"MouthFrown",
			"MouthFrownLeft",
			"MouthFrownRight",
			"MouthStretch",
			"MouthStretchLeft",
			"MouthStretchRight",
			"MouthSad",
			"MouthSadLeft",
			"MouthSadRight",
			"MouthDimple",
			"MouthDimpleLeft",
			"MouthDimpleRight",
			"MouthRaiser",
			"MouthRaiserUpper",
			"MouthRaiserLower",
			"MouthPress",
			"MouthPressLeft",
			"MouthPressRight",
			"MouthTightener",
			"MouthTightenerLeft",
			"MouthTightenerRight",
			"TongueOut",
			"TongueOutStep1",
			"TongueOutStep2",
			"TongueDown",
			"TongueUp",
			"TongueLeft",
			"TongueRight",
			"TongueUpLeftMorph",
			"TongueUpRightMorph",
			"TongueDownLeftMorph",
			"TongueDownRightMorph",
			"TongueRoll",
			"TongueBendDown",
			"TongueCurlUp",
			"TongueSquish",
			"TongueFlat",
			"TongueTwistLeft",
			"TongueTwistRight",
			"SoftPalateClose",
			"ThroatSwallow",
			"NeckFlexLeft",
			"NeckFlexRight",
		};

		public static readonly string[] SRanipal = new string[]
		{
			"Eye_Left_Left",
			"Eye_Right_Right",
			"Eye_Left_Right",
			"Eye_Right_Left",
			"Eye_Left_Up",
			"Eye_Right_Up",
			"Eye_Left_Down",
			"Eye_Right_Down",
			"Eye_Left_Blink",
			"Eye_Right_Blink",
			"Eye_Left_squeeze",
			"Eye_Right_squeeze",
			"Eye_Left_Wide",
			"Eye_Right_Wide",
			"Eye_Left_Dilation",
			"Eye_Right_Dilation",
			"Eye_Left_Constrict",
			"Eye_Right_Constrict",
			"Cheek_Puff_Left",
			"Cheek_Puff_Right",
			"Cheek_Suck",
			"Jaw_Open",
			"Mouth_Ape_Shape",
			"Jaw_Left",
			"Jaw_Right",
			"Jaw_Forward",
			"Mouth_Upper_Inside",
			"Mouth_Lower_Inside",
			"Mouth_O_Shape",
			"Mouth_Upper_Overturn",
			"Mouth_Lower_Overturn",
			"Mouth_Pout",
			"Mouth_Upper_UpLeft",
			"Mouth_Upper_UpRight",
			"Mouth_Lower_DownLeft",
			"Mouth_Lower_DownRight",
			"Mouth_Upper_Left",
			"Mouth_Lower_Left",
			"Mouth_Upper_Right",
			"Mouth_Lower_Right",
			"Mouth_Smile_Left",
			"Mouth_Smile_Right",
			"Mouth_Smile_Left",
			"Mouth_Smile_Right",
			"Mouth_Smile_Left",
			"Mouth_Smile_Right",
			"Mouth_Sad_Left",
			"Mouth_Sad_Right",
			"Mouth_Sad_Left",
			"Mouth_Sad_Right",
			"Mouth_Lower_Overlay",
			"Tongue_LongStep1",
			"Tongue_LongStep2",
			"Tongue_Down",
			"Tongue_Up",
			"Tongue_Left",
			"Tongue_Right",
			"Tongue_UpLeft_Morph",
			"Tongue_UpRight_Morph",
			"Tongue_DownLeft_Morph",
			"Tongue_DownRight_Morph",
			"Tongue_Roll",
		};

		public static readonly string[] ARKit = new string[]
		{
			"eyeLookOutLeft",
			"eyeLookOutRight",
			"eyeLookInLeft",
			"eyeLookInRight",
			"eyeLookUpLeft",
			"eyeLookUpRight",
			"eyeLookDownLeft",
			"eyeLookDownRight",
			"eyeBlinkLeft",
			"eyeBlinkRight",
			"eyeSquintLeft",
			"eyeSquintRight",
			"eyeWideLeft",
			"eyeWideRight",
			"browDownLeft",
			"browDownRight",
			"browDownLeft",
			"browDownRight",
			"browInnerUp",
			"browOuterUpLeft",
			"browOuterUpRight",
			"noseSneerLeft",
			"noseSneerRight",
			"cheekSquintLeft",
			"cheekSquintRight",
			"cheekPuff",
			"jawOpen",
			"mouthClose",
			"jawLeft",
			"jawRight",
			"jawForward",
			"mouthRollUpper",
			"mouthRollLower",
			"mouthFunnel",
			"mouthPucker",
			"mouthUpperUpLeft",
			"mouthUpperUpRight",
			"mouthLowerDownLeft",
			"mouthLowerDownRight",
			"mouthLeft",
			"mouthRight",
			"mouthSmileLeft",
			"mouthSmileRight",
			"mouthSmileLeft",
			"mouthSmileRight",
			"mouthSmileLeft",
			"mouthSmileRight",
			"mouthFrownLeft",
			"mouthFrownRight",
			"mouthStretchLeft",
			"mouthStretchRight",
			"mouthFrownLeft",
			"mouthFrownRight",
			"mouthDimpleLeft",
			"mouthDimpleRight",
			"mouthShrugUpper",
			"mouthShrugLower",
			"mouthPressLeft",
			"mouthPressRight",
			"tongueOut",
		};
	}
}

#endif
